spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      format_sql: true
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/sale_jpa
    username: root
    password: 123456

logging:
  level:
    org:
      springframework.web: DEBUG

server:
  error:
    include-message: always